# Generated by Django 3.2.15 on 2022-09-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pscmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['date']},
        ),
    ]
