# Generated by Django 3.2.15 on 2022-09-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pscmodels', '0003_alter_posts_creator'),
        ('pscmodels', '0004_alter_comments_active'),
    ]

    operations = [
    ]
