# Generated by Django 3.2.15 on 2022-09-29 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscmodels', '0005_merge_20220929_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='posts',
            name='upvotes',
            field=models.ManyToManyField(related_name='post_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
