# Generated by Django 3.2.15 on 2022-09-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscmodels', '0008_auto_20220929_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
