# Generated by Django 3.2.15 on 2022-09-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscmodels', '0009_alter_posts_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
