# Generated by Django 3.2.15 on 2022-09-30 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscmodels', '0010_alter_posts_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
