# Generated by Django 3.2.15 on 2022-09-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscmodels', '0011_posts_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
