# Generated by Django 3.2.15 on 2022-09-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pscmodels', '0012_newmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewManager',
        ),
    ]
