# Generated by Django 3.2.15 on 2022-10-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscmodels', '0015_remove_user_bio_remove_user_profile_pic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='img/post/'),
        ),
    ]
