# Generated by Django 4.1.1 on 2022-10-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscmodels', '0016_alter_posts_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
