# Generated by Django 4.1.1 on 2022-10-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscmodels', '0017_alter_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(),
        ),
    ]
